// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpknQTwoFuh63VAf4RUVrAVRLWk398kWA',
    appId: '1:389544414160:web:0d341907b559d9185147d5',
    messagingSenderId: '389544414160',
    projectId: 'quicklogin-4c663',
    authDomain: 'quicklogin-4c663.firebaseapp.com',
    storageBucket: 'quicklogin-4c663.firebasestorage.app',
    measurementId: 'G-HE889Q6DQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5nq9APGLXgc5lAwUyGNuVuOOWQsZFm74',
    appId: '1:389544414160:android:0d582ffabcde14cb5147d5',
    messagingSenderId: '389544414160',
    projectId: 'quicklogin-4c663',
    storageBucket: 'quicklogin-4c663.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJhgqMqq2Ef7I1QxOP2OGpUSdji5Vmg54',
    appId: '1:389544414160:ios:7635c39a3b24ab265147d5',
    messagingSenderId: '389544414160',
    projectId: 'quicklogin-4c663',
    storageBucket: 'quicklogin-4c663.firebasestorage.app',
    iosBundleId: 'com.example.quickLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJhgqMqq2Ef7I1QxOP2OGpUSdji5Vmg54',
    appId: '1:389544414160:ios:7635c39a3b24ab265147d5',
    messagingSenderId: '389544414160',
    projectId: 'quicklogin-4c663',
    storageBucket: 'quicklogin-4c663.firebasestorage.app',
    iosBundleId: 'com.example.quickLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpknQTwoFuh63VAf4RUVrAVRLWk398kWA',
    appId: '1:389544414160:web:ba6ae4f6d469d7fc5147d5',
    messagingSenderId: '389544414160',
    projectId: 'quicklogin-4c663',
    authDomain: 'quicklogin-4c663.firebaseapp.com',
    storageBucket: 'quicklogin-4c663.firebasestorage.app',
    measurementId: 'G-RKVJYEJ6XY',
  );

}